### PR TITLE
Add Tobias to the Team

### PR DESCRIPTION
**Pull request by toh82**
Well, what should I tell, I love to contributing to open source projects. I think I don't have enough side projects, so it's time for another one. Since I'm working with magento, my mind is walking around the topic to build an e-commerce system for the modern web, having offline first, PWA principles and all these things.

### CODE REVIEW

**Comment by dmanners** [comment]
Hi @toh82 thank you for your interest.

My first question is if you could add 1 thing to every project what would it be and why?

**Comment by sandermangel** [comment]
@toh82 awesome you PRd! So, now it's time for the interview round!
What kind of frontend vs. backend integration would you advise to use with KickAss? Rather read from APIs with some Fancy javascript library or have some good old fashioned views that get populated from a controller so you would have the data ready for styling

**Comment by toh82** [comment]
@dmanners 
dunno if this answer is valid but it would be a **diverse, open and involved community**, like in the hoodie project. 

**Why**: because the people in this community motivate each other a lot. From the very first moment, people are welcome heartily and it feels like you jump into a bunch of awesome friends. I've seen how much a project benefit from such a community and it is amazing.

If this isn't what you expected I would say **pwa and offline first** ;)

**Comment by toh82** [comment]
@sandermangel 
I would go for an approach of a headless core with interfaces. 
That could work over powerful search/content providers or directly with asking the core for data. Important is, that an e-commerce application can work offline, too. I don't mind if a storefront is build with js or php, both should be possible through the headless approach. Personally, I would use "modern" JS like ember or vuejs. Depending, on how the storefront should be I would also consider using backbonejs to have a very simple framework footprint. Maybe just a nodejs with es6 modules. 
I think for a good and quick start, the framework should be as simple as possible.

Sorry if some English words are confusing, I'm not so good in buzzwords.

**Comment by mkutyba** [comment]
Hi people!
@toh82 I don't know ember nor vuejs. There are a lot of weird things happening in JS world, new frameworks every day (not these two but generally). I remark, if it has to be KickAss project, it could involve more "mainstream" framework like react or angular. In fact react is also simple as possible, it isn't even a framework.

Anyway I think that JS would be better for making offline app/ PWA. And PWA is today's must have, especially due of mobile devices with faster and faster but lower quality internet connection.

**Comment by sandermangel** [comment]
@toh82 thanks for those answers. Very insightful! 
As candidate lead frontend there will also be a responsibility to make frontendend accessible to developers. As a backend developer I know the pain KnockoutJS has caused me on M2.
1. how do you see the balance between bleeding edge technology and frameworks vs. ease of use and accessibility as a dev
2. which steps would you propose to make the frontend of kickass easy to get started with

**Comment by toh82** [comment]
@sandermangel 

1. This is a very difficult topic and I talked already with the people behind hoodie about that, so I can say it depends. To know for whom we code is essential, for example in hoodie we keep things very simple, we do everything in vanilla js to provide a very fast entry point for developers. hoodie is developed for developers.  

Therefore I want to give back the question: "For whom do we build the project?" 
@dmanners @sandermangel @adam-paterson 

Personally, I'm not for a bleeding edge framework, at least not for the entry point. I tried already some of them and don't like how they appear, but I don't think we should discuss frameworks here. A framework, if used, has to be validated very carefully. But a no go is if you put frameworks together and use them in a strange way. It's better to go one strict and clear way. 

2. This depends a bit on (1.), but with KickAss I would love to go the same road as hoodie. If we go a way of a standalone storefront, it might be the best to work as vanilla as possible, so that devs can easy see the entry. This enables them to make their own storefronts with angular, etc and maybe provide them as repos which we can feature. What do we need for this, a very easy to use API, with a good documentation including the possibility to try out calls. For sure we also need a demo storefront with some general modules. I would love if we make it very modular, means a module could be, for example, a product view which provides an output for a list and also for detail or even smaller chunks. I love this because small modules are very readable and maintainable.

From a open source community perspective, we should make a plan on how and when we want to roll out for different ppl. Like first milestone is only for team members to provide the base, after this is done well and documented we can include the first developers into the system and let them check and communicate what they're missing to start working. As soon as we know and fixed that parts we can rollout for community devs. This can be made more granular by topics or event by states such as don't roll out before we have tests in our demo front, etc. We also have to take care about github issues, it is totally worth to provide very basic starter issues, at a certain point, to get ppl involved (I can tell more about that stuff in detail as soon as we started). 

Hope that fits your questions, so far.

**Comment by sandermangel** [comment]
@toh82 wow.... 
that's one awesome philosophy. You have my vote

**Review by sandermangel — APPROVED** [review]

**Comment by adam-paterson** [comment]
We need @toh82. +1 from me

**Review by dmanners — APPROVED** [review]

**Pull request merged**
