### PR TITLE
Add Adam to the Team

### PR DESCRIPTION
**Pull request by adam-paterson**
You have to accept this PR. I wrote it using VIM. And like I said. I'm excited.

### CODE REVIEW

**Comment by dmanners** [comment]
Thank you @adam-paterson for your application. With accordance to our KickAss employee rules you have now entered the 14 day, waiting and voting period. If we have questions or if you have question please use this PR to gather them.

Thank you and good luck.

**Comment by dmanners** [comment]
@adam-paterson I myself love symfony/serializer and want it in every project I do. @sandermangel love goaop and also wants that in every project he does. What 1 thing do you love so much that you would bring into this project?

**Comment by sandermangel** [comment]
@adam-paterson if you could name one things that can be found in every e-commerce project but is implemented in the wrong way every time due to technical limitations / time- or budget constrain / etc what would that be and how would you approach that issue in an ideal world

**Comment by adam-paterson** [comment]
@dmanners That's a tough one. With regards to favourite libraries I'm with @sandermangel with the `goaop/framework`. At the minute every project I undertake I have to have a Docker environment available. Something I've already started for KickAss. I'm always excited when I find a new library using Docker to allow people to boot up a development environment with ease.

@sandermangel I'd have to say I haven't found one e-commerce project that handles third party integrations well. Every build I've ever done has an integration with a PIM, CRM, etc. The majority of the requirements will be the same, with only the specific business logic being different. In an ideal world I'd have various reader, writer and parser adapters which are easily extendable for the business requirements.

**Comment by dmanners** [comment]
@adam-paterson super answers so far. I love your thoughts with regards to docker, I don't use it myself but I know people love it and so we should help out when we can. My next question:

What does the keyword `final` do and what are your thoughts on it's usage in the open source world?

**Comment by adam-paterson** [comment]
@dmanners  `final`prevents child classes from method overriding. If `final` is used on the class itself it the class itself cannot be extended.

I haven't seen it used in the OS world much at all and that is probably because there is a lot of confusion when to use a `final` class. I've not even used them that often.

From my understanding a final class should be used when they implement and interface and no other public methods are defined. The correct usage of `final` prevents a huge inheritance chain and forces the developer to think about composition and the public API.

**Comment by dmanners** [comment]
@adam-paterson one final, hahahah you get it, question from my side. What is your favorite chocolate based confectionery?

**Comment by adam-paterson** [comment]
@dmanners :1st_place_medal: Joke Award.

Not a big chocolate eater, but I'd say Reese's peanut butter cups are a strong contender.

**Comment by dmanners** [comment]
@adam-paterson ok let's open this up to the world outside of chocolate. What is your go to snack?

**Comment by adam-paterson** [comment]
@dmanners I'd rather skip snacks and grab a bottle of wine when the kids are in bed.

**Comment by adam-paterson** [comment]
@dmanners That wasn't a proposal.

**Review by dmanners — APPROVED** [review]
I am more than happy with this application!

**Pull request merged**
